//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apportionment2 {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = 
                        new global::System.Resources.ResourceManager("Apportionment2.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Create new participant.
        /// </summary>
        public static string AddNewParticipant {
            get {
                return ResourceManager.GetString("AddNewParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit participants.
        /// </summary>
        public static string AddRemoveUserTabPageTitle {
            get {
                return ResourceManager.GetString("AddRemoveUserTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add in all pots.
        /// </summary>
        public static string AddUserPageAddInAllPots {
            get {
                return ResourceManager.GetString("AddUserPageAddInAllPots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add in this pot.
        /// </summary>
        public static string AddUserPageAddInThisPot {
            get {
                return ResourceManager.GetString("AddUserPageAddInThisPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddUserPageAddUserButton {
            get {
                return ResourceManager.GetString("AddUserPageAddUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string AddUserPageModeLabel {
            get {
                return ResourceManager.GetString("AddUserPageModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot participants.
        /// </summary>
        public static string AddUserPagePotsUsers {
            get {
                return ResourceManager.GetString("AddUserPagePotsUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from other pots.
        /// </summary>
        public static string AddUserPageSelectFromOtherPotsLabel {
            get {
                return ResourceManager.GetString("AddUserPageSelectFromOtherPotsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Add.
        /// </summary>
        public static string AddUserPageTitel {
            get {
                return ResourceManager.GetString("AddUserPageTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of new participant.
        /// </summary>
        public static string AddUserPageUserNameEntryPlaceholder {
            get {
                return ResourceManager.GetString("AddUserPageUserNameEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other users was not found.
        /// </summary>
        public static string AlertMessNoOtherUsers {
            get {
                return ResourceManager.GetString("AlertMessNoOtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying find other participants.
        /// </summary>
        public static string AlertTitleNoOtherUsers {
            get {
                return ResourceManager.GetString("AlertTitleNoOtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itog.
        /// </summary>
        public static string CalcApportionItog {
            get {
                return ResourceManager.GetString("CalcApportionItog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string CalcApportionMenuButton {
            get {
                return ResourceManager.GetString("CalcApportionMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CalcApportionPageAdd {
            get {
                return ResourceManager.GetString("CalcApportionPageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new pot.
        /// </summary>
        public static string CalcApportionPageAddPot {
            get {
                return ResourceManager.GetString("CalcApportionPageAddPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add participant.
        /// </summary>
        public static string CalcApportionPageAddUser {
            get {
                return ResourceManager.GetString("CalcApportionPageAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name.
        /// </summary>
        public static string CostsPageATripNameEntryPlaceholder
        {
            get
            {
                return ResourceManager.GetString("CostsPageATripNameEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to borrowed.
        /// </summary>
        public static string CalcApportionPageBorrowed {
            get {
                return ResourceManager.GetString("CalcApportionPageBorrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string CalcApportionPageCalc {
            get {
                return ResourceManager.GetString("CalcApportionPageCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue  the journey.
        /// </summary>
        public static string CalcApportionPageContinueJourney {
            get {
                return ResourceManager.GetString("CalcApportionPageContinueJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey is resumed.
        /// </summary>
        public static string CalcApportionPageContinueJourneyMessage {
            get {
                return ResourceManager.GetString("CalcApportionPageContinueJourneyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add debt.
        /// </summary>
        public static string CalcApportionPageDebt {
            get {
                return ResourceManager.GetString("CalcApportionPageDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CalcApportionPageDeletePot {
            get {
                return ResourceManager.GetString("CalcApportionPageDeletePot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string CalcApportionPageEditPot {
            get {
                return ResourceManager.GetString("CalcApportionPageEditPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End the journey.
        /// </summary>
        public static string CalcApportionPageEndJourney {
            get {
                return ResourceManager.GetString("CalcApportionPageEndJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey is over.
        /// </summary>
        public static string CalcApportionPageEndJourneyMessage {
            get {
                return ResourceManager.GetString("CalcApportionPageEndJourneyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could  not delete the pot. Must be one pot..
        /// </summary>
        public static string CalcApportionPageErrorDeleteLastPotMessage {
            get {
                return ResourceManager.GetString("CalcApportionPageErrorDeleteLastPotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could  not delete the pot. Sum is not null..
        /// </summary>
        public static string CalcApportionPageErrorDeleteMessage {
            get {
                return ResourceManager.GetString("CalcApportionPageErrorDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete pot..
        /// </summary>
        public static string CalcApportionPageErrorDeleteTitle {
            get {
                return ResourceManager.GetString("CalcApportionPageErrorDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string CalcApportionPageExit {
            get {
                return ResourceManager.GetString("CalcApportionPageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the journey.
        /// </summary>
        public static string CalcApportionPageExitFromProj {
            get {
                return ResourceManager.GetString("CalcApportionPageExitFromProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy journey id to clipboard.
        /// </summary>
        public static string CalcApportionPageGetAppId {
            get {
                return ResourceManager.GetString("CalcApportionPageGetAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailes.
        /// </summary>
        public static string CalcApportionPageInfoByPot {
            get {
                return ResourceManager.GetString("CalcApportionPageInfoByPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id was copied to the clipboard.
        /// </summary>
        public static string CalcApportionPageJGetAppIdMessage {
            get {
                return ResourceManager.GetString("CalcApportionPageJGetAppIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey data was sent to the cloud. Id was copied to the clipboard.
        /// </summary>
        public static string CalcApportionPageJourneyIsSyncMessage {
            get {
                return ResourceManager.GetString("CalcApportionPageJourneyIsSyncMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lent.
        /// </summary>
        public static string CalcApportionPageLent {
            get {
                return ResourceManager.GetString("CalcApportionPageLent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string CalcApportionPageMenuTitle {
            get {
                return ResourceManager.GetString("CalcApportionPageMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New pot.
        /// </summary>
        public static string CalcApportionPageNewPot {
            get {
                return ResourceManager.GetString("CalcApportionPageNewPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New expense.
        /// </summary>
        public static string CalcApportionPageNewPotItem {
            get {
                return ResourceManager.GetString("CalcApportionPageNewPotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next payer.
        /// </summary>
        public static string CalcApportionPageNextPayerLabel {
            get {
                return ResourceManager.GetString("CalcApportionPageNextPayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the pot.
        /// </summary>
        public static string CalcApportionPagePotListTitle {
            get {
                return ResourceManager.GetString("CalcApportionPagePotListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync journey.
        /// </summary>
        public static string CalcApportionPageSync {
            get {
                return ResourceManager.GetString("CalcApportionPageSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string CalcApportionPageUsers {
            get {
                return ResourceManager.GetString("CalcApportionPageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey.
        /// </summary>
        public static string CaptionJourney {
            get {
                return ResourceManager.GetString("CaptionJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant name.
        /// </summary>
        public static string CaptionParticipantName {
            get {
                return ResourceManager.GetString("CaptionParticipantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot name.
        /// </summary>
        public static string CaptionPotName {
            get {
                return ResourceManager.GetString("CaptionPotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string CaptionShare {
            get {
                return ResourceManager.GetString("CaptionShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characterisic.
        /// </summary>
        public static string Characteristic {
            get {
                return ResourceManager.GetString("Characteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinking..
        /// </summary>
        public static string CharacteristicAlco {
            get {
                return ResourceManager.GetString("CharacteristicAlco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гусар. Любит шикануть, но умеет вовремя остановиться. Часто предлагает заплатить по счету, но с удовольствием уступает эту привилегию меценату. .
        /// </summary>
        public static string CharacteristicSumSpendAboveMiddle {
            get {
                return ResourceManager.GetString("CharacteristicSumSpendAboveMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меценат. Щедр, иногда излишне. Платит за всех и за все. Если и не душа, то уж точно кошелек компании..
        /// </summary>
        public static string CharacteristicSumSpendMax {
            get {
                return ResourceManager.GetString("CharacteristicSumSpendMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экономист.Разумно щедр: не расточителен, но и не скуп. Находит общий язык со своей внутренней жабой..
        /// </summary>
        public static string CharacteristicSumSpendMiddle {
            get {
                return ResourceManager.GetString("CharacteristicSumSpendMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должник.Жаден. Придерживает свои кровные до последнего. Коллектив его пока терпит..
        /// </summary>
        public static string CharacteristicSumSpendMin {
            get {
                return ResourceManager.GetString("CharacteristicSumSpendMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a nonzero value!.
        /// </summary>
        public static string DebtEditPageMessgeAlertSumZero {
            get {
                return ResourceManager.GetString("DebtEditPageMessgeAlertSumZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should not be zero.
        /// </summary>
        public static string DebtEditPageTitleAlertSumZero {
            get {
                return ResourceManager.GetString("DebtEditPageTitleAlertSumZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add debt.
        /// </summary>
        public static string DebtPageAdd {
            get {
                return ResourceManager.GetString("DebtPageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts.
        /// </summary>
        public static string DebtPageDebtsLabel {
            get {
                return ResourceManager.GetString("DebtPageDebtsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete debt.
        /// </summary>
        public static string DebtPageDelete {
            get {
                return ResourceManager.GetString("DebtPageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit debt.
        /// </summary>
        public static string DebtPageEdit {
            get {
                return ResourceManager.GetString("DebtPageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On main page.
        /// </summary>
        public static string DebtPageGoToMain {
            get {
                return ResourceManager.GetString("DebtPageGoToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string DebtPageMenu {
            get {
                return ResourceManager.GetString("DebtPageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor.
        /// </summary>
        public static string DebtsViewModelCreditor {
            get {
                return ResourceManager.GetString("DebtsViewModelCreditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debitor.
        /// </summary>
        public static string DebtsViewModelDebitor {
            get {
                return ResourceManager.GetString("DebtsViewModelDebitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string DebtsViewModelSum {
            get {
                return ResourceManager.GetString("DebtsViewModelSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Create new pot.
        /// </summary>
        public static string EditPotItemPageItemCreateNewPot {
            get {
                return ResourceManager.GetString("EditPotItemPageItemCreateNewPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the expense.
        /// </summary>
        public static string EditPotItemPageItemNamePlaceHolder {
            get {
                return ResourceManager.GetString("EditPotItemPageItemNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the expense.
        /// </summary>
        public static string EditPotItemPageMessageAlertNameEmpty {
            get {
                return ResourceManager.GetString("EditPotItemPageMessageAlertNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the pot!.
        /// </summary>
        public static string EditPotItemPageMessageAlertPotEmpty {
            get {
                return ResourceManager.GetString("EditPotItemPageMessageAlertPotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payers:.
        /// </summary>
        public static string EditPotItemPagePayersButton {
            get {
                return ResourceManager.GetString("EditPotItemPagePayersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the pot.
        /// </summary>
        public static string EditPotItemPagepickerPotChoiceLabel {
            get {
                return ResourceManager.GetString("EditPotItemPagepickerPotChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the expense.
        /// </summary>
        public static string EditPotItemPagePotItemNameLabel {
            get {
                return ResourceManager.GetString("EditPotItemPagePotItemNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the pot.
        /// </summary>
        public static string EditPotItemPageSetPotButton {
            get {
                return ResourceManager.GetString("EditPotItemPageSetPotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of expense.
        /// </summary>
        public static string EditPotItemPageTitleAlertNameEmpty {
            get {
                return ResourceManager.GetString("EditPotItemPageTitleAlertNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot is not selected.
        /// </summary>
        public static string EditPotItemPageTitleAlertPotEmpty {
            get {
                return ResourceManager.GetString("EditPotItemPageTitleAlertPotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditUserPageTitle {
            get {
                return ResourceManager.GetString("EditUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string LoadApportionPageDeleteApportionment {
            get {
                return ResourceManager.GetString("LoadApportionPageDeleteApportionment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схема взаиморасчетов.
        /// </summary>
        public static string NettingScheme {
            get {
                return ResourceManager.GetString("NettingScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        public static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take from another journey.
        /// </summary>
        public static string ParticipiantFromAnotherTrips {
            get {
                return ResourceManager.GetString("ParticipiantFromAnotherProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot.
        /// </summary>
        public static string Pot {
            get {
                return ResourceManager.GetString("Pot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove participant.
        /// </summary>
        public static string PotItemPageAddRemoveUser {
            get {
                return ResourceManager.GetString("PotItemPageAddRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the expense.
        /// </summary>
        public static string PotItemPageSelectEntryPlaceholder {
            get {
                return ResourceManager.GetString("PotItemPageSelectEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select participant.
        /// </summary>
        public static string PotItemPageSelectUserLabel {
            get {
                return ResourceManager.GetString("PotItemPageSelectUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string PotPageAddItem {
            get {
                return ResourceManager.GetString("PotPageAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string PotPageAddUser {
            get {
                return ResourceManager.GetString("PotPageAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item.
        /// </summary>
        public static string PotPageDeletePotItem {
            get {
                return ResourceManager.GetString("PotPageDeletePotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        public static string PotPageEditPotItem {
            get {
                return ResourceManager.GetString("PotPageEditPotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back on main.
        /// </summary>
        public static string PotPageGoToMain {
            get {
                return ResourceManager.GetString("PotPageGoToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itog pot.
        /// </summary>
        public static string PotPageItog {
            get {
                return ResourceManager.GetString("PotPageItog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string PotPageMenuButton {
            get {
                return ResourceManager.GetString("PotPageMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string PotPageMenuTitle {
            get {
                return ResourceManager.GetString("PotPageMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is empty.Please, enter the name!.
        /// </summary>
        public static string PotPageMessageAlertNameEmpty {
            get {
                return ResourceManager.GetString("PotPageMessageAlertNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No participant in the pot! Please, add participants!.
        /// </summary>
        public static string PotPageMessageAlertNeedPotUsers {
            get {
                return ResourceManager.GetString("PotPageMessageAlertNeedPotUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to another pot.
        /// </summary>
        public static string PotPageMovePageItem {
            get {
                return ResourceManager.GetString("PotPageMovePageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot name.
        /// </summary>
        public static string PotPagePotNamePlaceHolder {
            get {
                return ResourceManager.GetString("PotPagePotNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is empty.
        /// </summary>
        public static string PotPageTitleAlertNameEmpty {
            get {
                return ResourceManager.GetString("PotPageTitleAlertNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No participants in the pot!.
        /// </summary>
        public static string PotPageTitleAlertNeedPotUsers {
            get {
                return ResourceManager.GetString("PotPageTitleAlertNeedPotUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without pot.
        /// </summary>
        public static string PotUserPageCreateUserWithoutPot {
            get {
                return ResourceManager.GetString("PotUserPageCreateUserWithoutPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete participant.
        /// </summary>
        public static string RemoveUserDelete {
            get {
                return ResourceManager.GetString("RemoveUserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant can not be removed from all pots. he paid in the following pots:.
        /// </summary>
        public static string RemoveUserPageCanNotRemoveFromAllPotsMess {
            get {
                return ResourceManager.GetString("RemoveUserPageCanNotRemoveFromAllPotsMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant can not be deleted. He paid in the following apportionments:.
        /// </summary>
        public static string RemoveUserPageCanNotRemoveFromApportionsMess {
            get {
                return ResourceManager.GetString("RemoveUserPageCanNotRemoveFromApportionsMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant can not be removed. he paid for the following expenses:.
        /// </summary>
        public static string RemoveUserPageCanNotRemoveMess {
            get {
                return ResourceManager.GetString("RemoveUserPageCanNotRemoveMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from all pots.
        /// </summary>
        public static string RemoveUserPageFromAllPot {
            get {
                return ResourceManager.GetString("RemoveUserPageFromAllPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from this pot.
        /// </summary>
        public static string RemoveUserPageFromThisPot {
            get {
                return ResourceManager.GetString("RemoveUserPageFromThisPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant can not be removed.
        /// </summary>
        public static string RemoveUserPageMessTitle {
            get {
                return ResourceManager.GetString("RemoveUserPageMessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string RemoveUserPageMode {
            get {
                return ResourceManager.GetString("RemoveUserPageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot participants.
        /// </summary>
        public static string RemoveUserPagePotUsersLabel {
            get {
                return ResourceManager.GetString("RemoveUserPagePotUsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an existing participant.
        /// </summary>
        public static string RemoveUserPageRemoveExistingUserLabel {
            get {
                return ResourceManager.GetString("RemoveUserPageRemoveExistingUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Remove.
        /// </summary>
        public static string RemoveUserPageTitle {
            get {
                return ResourceManager.GetString("RemoveUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itog.
        /// </summary>
        public static string ResultApportionmentPageItog {
            get {
                return ResourceManager.GetString("ResultApportionmentPageItog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta.
        /// </summary>
        public static string ResultApportionmentPagePerDelta {
            get {
                return ResourceManager.GetString("ResultApportionmentPagePerDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerParticipant.
        /// </summary>
        public static string ResultApportionmentPagePerUser {
            get {
                return ResourceManager.GetString("ResultApportionmentPagePerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot.
        /// </summary>
        public static string ResultApportionmentPagePotName {
            get {
                return ResourceManager.GetString("ResultApportionmentPagePotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string ResultApportionmentPageSaved {
            get {
                return ResourceManager.GetString("ResultApportionmentPageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save result.
        /// </summary>
        public static string TripResultPageSaveInFileButton {
            get {
                return ResourceManager.GetString("ResultApportionmentPageSaveInFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spend.
        /// </summary>
        public static string ResultApportionmentPageSpend {
            get {
                return ResourceManager.GetString("ResultApportionmentPageSpend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total payable.
        /// </summary>
        public static string ResultApportionmentPageTotalPay {
            get {
                return ResourceManager.GetString("ResultApportionmentPageTotalPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total return.
        /// </summary>
        public static string ResultApportionmentPageTotalReturn {
            get {
                return ResourceManager.GetString("ResultApportionmentPageTotalReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string ResultApportionmentPageUsers {
            get {
                return ResourceManager.GetString("ResultApportionmentPageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set share for participants.
        /// </summary>
        public static string SetSharePageLabel {
            get {
                return ResourceManager.GetString("SetSharePageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set share.
        /// </summary>
        public static string SetSharePageTitle {
            get {
                return ResourceManager.GetString("SetSharePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About app.
        /// </summary>
        public static string StartMenuItemAbout {
            get {
                return ResourceManager.GetString("StartMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string StartMenuItemExit {
            get {
                return ResourceManager.GetString("StartMenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string StartMenuItemHelp {
            get {
                return ResourceManager.GetString("StartMenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load journey.
        /// </summary>
        public static string StartMenuItemLoad {
            get {
                return ResourceManager.GetString("StartMenuItemLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new journey.
        /// </summary>
        public static string StartMenuItemStart {
            get {
                return ResourceManager.GetString("StartMenuItemStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from cloud.
        /// </summary>
        public static string StartMenuItemSyncWithAzure {
            get {
                return ResourceManager.GetString("StartMenuItemSyncWithAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st pot.
        /// </summary>
        public static string StartPage1stPot {
            get {
                return ResourceManager.GetString("StartPage1stPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New journey.
        /// </summary>
        public static string StartPageNewProject {
            get {
                return ResourceManager.GetString("StartPageNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of the journey was failed.Check the apportionment id and try again..
        /// </summary>
        public static string SyncApportionmentPageSyncFailedMessage {
            get {
                return ResourceManager.GetString("SyncApportionmentPageSyncFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of the journey was failed..
        /// </summary>
        public static string SyncApportionmentPageSyncFailedMessageTitle {
            get {
                return ResourceManager.GetString("SyncApportionmentPageSyncFailedMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total must pay.
        /// </summary>
        public static string TotalMustPay {
            get {
                return ResourceManager.GetString("TotalMustPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total overtpaid.
        /// </summary>
        public static string TotalOverpaid {
            get {
                return ResourceManager.GetString("TotalOverpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string UserPageContactsButtom {
            get {
                return ResourceManager.GetString("UserPageContactsButtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the new name.
        /// </summary>
        public static string UserViewModelInputName {
            get {
                return ResourceManager.GetString("UserViewModelInputName", resourceCulture);
        }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserViewModelUserName {
            get {
                return ResourceManager.GetString("UserViewModelUserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string FormatDate
        {
            get
            {
                return ResourceManager.GetString("yyyy-MM-dd HH-mm-ss", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DefaultCurrencyCode
        {
            get
            {
                return ResourceManager.GetString("DefaultCurrencyCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AddNewPayer
        {
            get
            {
                return ResourceManager.GetString("AddNewPayer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string CostPageCostNamePlaceholder
        {
            get
            {
                return ResourceManager.GetString("CostPageCostNamePlaceholder", resourceCulture);
            }
        }

        public static string CostPageCostNameEmptyAlert
        {
            get
            {
                return ResourceManager.GetString("CostPageCostNameEmptyAlert", resourceCulture);
            }
        }

        public static string CostPageCostNameEmptyAlertMessage
        {
            get
            {
                return ResourceManager.GetString("CostPageCostNameEmptyAlertMessage", resourceCulture);
            }
        }

        public static string CostPagePayments
        {
            get
            {
                return ResourceManager.GetString("CostPagePayments", resourceCulture);
            }
        }

        public static string CostPageUnsavedDataAlertTitle
        {
            get
            {
                return ResourceManager.GetString("CostPageUnsavedDataAlertTitle", resourceCulture);
            }
        }

        public static string CostPageUnsavedDataAlertMessage
        {
            get
            {
                return ResourceManager.GetString("CostPageUnsavedDataAlertMessage", resourceCulture);
            }
        }

        public static string Yes
        {
            get
            {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        public static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        public static string CostPageAddPayment
        {
            get
            {
                return ResourceManager.GetString("CostPageAddPayment", resourceCulture);
            }
        }

        public static string CostPageAddParticipant
        {
            get
            {
                return ResourceManager.GetString("CostPageAddParticipant", resourceCulture);
            }
        }

        public static string CostPageAddNewCurrencies
        {
            get
            {
                return ResourceManager.GetString("CostPageAddNewCurrencies", resourceCulture);
            }
        }

        public static string CostsPageCurrencies
        {
            get
            {
                return ResourceManager.GetString("CostsPageCurrencies", resourceCulture);
            }
        }
        public static string CostsPageRenameTrip
        {
            get
            {
                return ResourceManager.GetString("CostsPageRenameTrip", resourceCulture);
            }
        }
        public static string CostsPageDeleteCostValue
        {
            get
            {
                return ResourceManager.GetString("CostsPageDeleteCostValue", resourceCulture);
            }
        }

        public static string CostsPageDeleteUserShareMessage
        {
            get
            {
                return ResourceManager.GetString("CostsPageDeleteUserShareMessage", resourceCulture);
            }
        }

        public static string CostsPageAddAllRatesMessage
        {
            get
            {
                return ResourceManager.GetString("CostsPageAddAllRatesMessage", resourceCulture);
            }
        }

        public static string CostsPageDeleteCost
        {
            get
            {
                return ResourceManager.GetString("CostsPageDeleteCost", resourceCulture);
            }
        }
        
        public static string CostsPageDeleteCostMessage
        {
            get
            {
                return ResourceManager.GetString("CostsPageDeleteCostMessage", resourceCulture);
            }
        }

        public static string CostsPageCopyCost
        {
            get
            {
                return ResourceManager.GetString("CostsPageCopyCost", resourceCulture);
            }
        }

        public static string TripResultPageNoShare
        {
            get
            {
                return ResourceManager.GetString("TripResultPageNoShare", resourceCulture);
            }
        }

        public static string TripResultPageShareFile
        {
            get
            {
                return ResourceManager.GetString("TripResultPageShareFile", resourceCulture);
            }
        }

      
        public static string TripCurrenciesPageBaseCurrency
        {
            get
            {
                return ResourceManager.GetString("TripCurrenciesPageBaseCurrency", resourceCulture);
            }
        }

        public static string TripCurrenciesPageExchangeRates
        {
            get
            {
                return ResourceManager.GetString("TripCurrenciesPageExchangeRates", resourceCulture);
            }
        }

        public static string TripCurrenciesPageDeleteCurrencyFromTrip
        {
            get
            {
                return ResourceManager.GetString("TripCurrenciesPageDeleteCurrencyFromTrip", resourceCulture);
            }
        }

        public static string TripCurrenciesPageCanNotDeleteCurrencyFromTrip
        {
            get
            {
                return ResourceManager.GetString("TripCurrenciesPageCanNotDeleteCurrencyFromTrip", resourceCulture);
            }
        }

        public static string TripCurrenciesPageSetBaseCurrencyMessage
        {
            get
            {
                return ResourceManager.GetString("TripCurrenciesPageSetBaseCurrencyMessage", resourceCulture);
            }
        }

        public static string TripNamePageTripNamePlaceholder
        {
            get
            {
                return ResourceManager.GetString("TripNamePageTripNamePlaceholder", resourceCulture);
            }
        }

        public static string TripNamePageDataStartLabel
        {
            get
            {
                return ResourceManager.GetString("TripNamePageDataStartLabel", resourceCulture);
            }
        }

        public static string TripNamePageDataEndLabel
        {
            get
            {
                return ResourceManager.GetString("TripNamePageDataEndLabel", resourceCulture);
            }
        }

        public static string TripListPageRenameTrip
        {
            get
            {
                return ResourceManager.GetString("TripListPageRenameTrip", resourceCulture);
            }
        }

        public static string TripListPageDeleteTrip
        {
            get
            {
                return ResourceManager.GetString("TripListPageDeleteTrip", resourceCulture);
            }
        }

        public static string TripListPageDeleteTripMessage
        {
            get
            {
                return ResourceManager.GetString("TripListPageDeleteTripMessage", resourceCulture);
            }
        }
    }
}
